- src/assets/animals.json
The cockroaches seem not to have actually been evaluated yet.
> Fix IUCN status for cockroaches

- src/pages/overlay/components/AmbassadorList.tsx
Resolves #9
Tested in current Chrome, FF and Safari
> Scroll to active animal on selection

- .env.sample
- README.md
:wave: Was just spinning this up locally for development and figured I'd add a few more notes around the process for testing the extension on Twitch
> Improved development setup notes

- src/assets/ambassadors.json
Per Maya in Discord
cc https://github.com/alveusgg/alveusgg/pull/137
> Abbott was born in May 2020

- src/assets/ambassadors.json
Added IUCN ids to the site last night, and noticed a couple of statuses were incorrect: https://github.com/alveusgg/alveusgg/pull/139
> Updated IUCN status for ambassadors

- src/pages/overlay/components/activationButtons/ActivationButtons.tsx
- src/pages/overlay/components/activationButtons/activationButtons.module.scss
- src/pages/overlay/components/overlay/Overlay.tsx
[Issue 57](https://github.com/abdullahmorrison/AlveusTwitchExtension/issues/57)
> Make activation buttons stay highlighted when clicked

- LICENSE.md
- package.json
👋 Adding the same license as in the alveusgg + data repositories, based on discussions in Discord. Please shout if you have any issues with adding it to this project :)
> Add license file + package json reference

- package-lock.json
- src/pages/overlay/components/ambassadorList/AmbassadorList.tsx
- src/pages/overlay/components/overlay/Overlay.tsx
- src/pages/panel/components/ambassadorPanel/AmbassadorPanel.tsx
- src/utils/ambassdaors.ts
- src/utils/chatCommand.ts
- src/utils/global/ambassadorButton/AmbassadorButton.tsx
- src/utils/global/ambassadorCard/AmbassadorCard.tsx
- src/utils/helpers.ts
cc https://github.com/alveusgg/data/pull/10
> Add data for retired ambassadors

- package-lock.json
- src/utils/ambassdaors.ts
- src/utils/global/ambassadorButton/AmbassadorButton.tsx
- src/utils/global/ambassadorCard/AmbassadorCard.tsx
cc https://github.com/alveusgg/data/pull/14
> Use ambassador image positions from data repository

- src/pages/overlay/App.tsx
- src/pages/overlay/components/overlay/Overlay.tsx
- src/pages/overlay/components/overlay/settings/Settings.tsx
Resolves #96 by adding an actual option in the UI
The alternative would be to use a env flag or command on the console
> Add option to prevent app from hiding in dev

- src/utils/chatCommand.ts
Toggling the prevent popups toggle should now actually prevent popups as expected
> Fix connection race in chat client

- .env.sample
- src/utils/chatCommand.ts
With the extension being available for anyone during collabs, probably would be useful to have some more accounts that always have access to help/debug
> Allow multiple privileged users

- package-lock.json
cc https://github.com/alveusgg/data/pull/25
> Update data (remove ducky, update images)

- src/utils/ambassadors.ts
- src/utils/global/ambassadorCard/AmbassadorCard.tsx
cc https://github.com/alveusgg/data/pull/22
> Add native to information on ambassador cards

- package-lock.json
- package.json
See https://github.com/alveusgg/data/pull/56
> Add push pop (update data)

- package-lock.json
- package.json
- src/components/ambassadorCard/AmbassadorCard.tsx
- src/hooks/useChatCommand.ts
cc https://github.com/alveusgg/data/pull/68
> Use chat commands from data package

- package-lock.json
- package.json
See: https://github.com/alveusgg/data/pull/72 and https://github.com/alveusgg/data/pull/73
> Improved stompy mission and wolf hybrid wording (data update)

- package-lock.json
- package.json
- src/components/ambassadorCard/AmbassadorCard.tsx
> Add confetti for birthday

- package-lock.json
- package.json
cc https://github.com/alveusgg/data/pull/74
> Update data (new images for Awa + Timber)

- src/components/Welcome.tsx
https://github.com/alveusgg/alveusgg/pull/700 never made it to here.
> Remove "exotic" mentions in content

- .lintstagedrc.json
- package.json
- src/pages/overlay/globals.css
- src/pages/panel/globals.css
- src/template.html
With the removal of SCSS in #183 I forgot to update Prettier as such.
> Run prettier on CSS + HTML, not SCSS

- package-lock.json
- package.json
cc https://github.com/alveusgg/data/pull/82
> Update data (fix Tailwind extend)

- package-lock.json
- package.json
- src/hooks/useAmbassadors.ts
cc https://github.com/alveusgg/data/pull/84
> Update data (mark Nilla Wafer as retired)

- src/components/AmbassadorCard.tsx
> Add ambassador species lifespans

- package-lock.json
- package.json
- src/components/AmbassadorCard.tsx
- src/components/Tooltip.tsx
- src/hooks/useAmbassadors.tsx
- src/pages/overlay/components/Buttons.tsx
- src/pages/overlay/components/overlay/Overlay.tsx
- src/pages/overlay/hooks/useIntelligentTimer.ts
- src/pages/overlay/hooks/useSettings.tsx
- src/pages/overlay/hooks/useSleeping.tsx
Closes #200. No peer dep issues reported by npm.
Of note, please check that the ref logic for the ambassador card (for transitions iirc) is working as expected, and that tooltips are working correctly with mouse entering.
As with https://github.com/alveusgg/alveusgg/pull/908, implements all the React 19 changes except for useRef cleanups as the old method still works for now.
> Update to React 19

- package.json
- pnpm-lock.yaml
> Fix dependency overrides for pnpm

- .github/dependabot.yml
https://github.com/alveusgg/alveusgg/pull/1102 but here.
> Create single dependabot group for minor/patch Actions updates

- src/hooks/useAmbassadors.tsx
- src/utils/dateManager.ts
> Use Alveus timezone for ambassador hook date check

- src/components/AmbassadorCard.tsx
- src/components/icons/IconExternal.tsx
- src/hooks/useAmbassadors.tsx
- src/pages/overlay/components/overlay/Ambassadors.tsx
- src/pages/overlay/components/overlay/Overlay.tsx
cc https://github.com/alveusgg/alveusgg/pull/1166
> Add enclosure to ambassador cards

- .github/dependabot.yml
Carrying this over from https://github.com/alveusgg/alveusgg/pull/1226
> Add @headlessui/react to tailwind Dependabot group

- package.json
- pnpm-lock.yaml
- src/hooks/useAmbassadors.tsx
Resolves #307. cc https://github.com/alveusgg/data/pull/164
> Update to Zod 4

- package.json
- pnpm-lock.yaml
- src/hooks/useAmbassadors.tsx
cc https://github.com/alveusgg/alveusgg/pull/1361 https://github.com/alveusgg/data/pull/178
> Bump zod from 3.25.76 to 4.0.5
