- src/assets/animals.json
I think according to my google searches the common spelling of black-tufted is so. They are also sometimes called black-pencilled marmosets.
See e.g. https://en.wikipedia.org/wiki/Black-tufted_marmoset
> black-tufted instead of black tuffed marmoset

- .gitignore
- .idea/scopes/Extension.xml
- README.md
Further to #17, this adds more to the README on running the extension, including covering the twitch developer rig.
This also adds an intellij workspace scope to mirror the CSS file exclusion for vscode.
> Further development note improvements

- src/pages/overlay/App.module.scss
- src/pages/overlay/App.tsx
- src/pages/overlay/components/disableChatPopup/DisableChatPopup.tsx
- src/pages/overlay/components/disableChatPopup/disableChatPopup.module.scss
- src/pages/overlay/components/overlay/overlay.module.scss
- src/pages/overlay/components/overlaySettings/overlaySettings.module.scss
👋 I made a couple of design tweaks to the disable popups toggle that I think will make it visually easier to understand, aligning it more with standard UI components found across the web etc.
This changes the wording to show the current state, rather than what the toggle would do by changing it, which I think provides more definitive language.
I've also added color to the toggle, to help aid with visually understanding if it is enabled or not -- as part of this, I've flipped what the toggle actually shows, with it now being "checked" when popups are enabled, which to me again feels more conventional for UI.
This also tweaks the position of the toggle on the page to match the height of the main overlay toggle, which I think provides a bit more visual consistency for the overlay.
(This also …
> Tweaked design for disable popup toggle

- src/pages/overlay/App.tsx
Fixes #31 which I accidentally caused in #29 with the input becoming a controlled input.
With the state as `false` by default and the setting loading via a hook, it allowed React to emit a change for it to that value in the same tick. Switching to lazy initialization of the state ensures that the initial value is whatever should be loaded from local storage.
> Use lazy initialization of settings to avoid race

- src/pages/overlay/App.module.scss
- src/pages/overlay/App.tsx
Resolves #41 
I would have preferred to use `onScroll` here, but it needs to be a capturing event listener so you get scroll events from any children, so had to use a ref instead.
Also fixed a TS error that I had introduced with the lazy settings state that I had missed before.
> Treat scrolling as an interaction to keep extension awake

- src/index.scss
- src/pages/overlay/App.module.scss
- src/pages/overlay/components/activationButtons/activationButtons.module.scss
- src/pages/overlay/components/ambassadorList/AmbassadorList.tsx
- src/pages/overlay/components/ambassadorList/ambassadorList.module.scss
- src/pages/overlay/components/overlay/overlay.module.scss
- src/pages/overlay/components/overlaySettings/overlaySettings.module.scss
- src/pages/overlay/index.scss
- src/pages/panel/components/ambassadorPanel/AmbassadorPanel.tsx
- src/pages/panel/components/ambassadorPanel/ambassadorPanel.module.scss
- src/pages/panel/components/nav/nav.module.scss
- src/utils/compositions/ambassador/ambassador.module.scss
- src/utils/global/ambassadorButton/ambassadorButton.module.scss
- src/utils/global/ambassadorCard/ambassadorCard.module.scss
- src/variables.scss
My first attempt on the improved scaling.
- Instead of scaling everything with `scale()` i opted to scale the list components separately with some `calc(x * clamp())` math to keep the scaling within bounds. With that we can make the list always use the full height of the overlay container which i have positioned to keep the recommended 5rem (=50px) space above and below.
- I moved the arrows above the list. I am not sure if you actually wanted that
- I added a `mask-image` to fade out the ambassador list
- I kept the previous scaling method for the card (using scale transforms) but added some more steps
Resolves #24
> Improve overlay scaling

- package-lock.json
- package.json
More work toward #36 -- this is a very minimal change, just organising and cleaning up the dependencies in the project (removing unused things, moving build-time things to dev dependencies), and running eslint as part of the lint command (which is run by the test workflow).
Felt it made sense to get at least the basic eslint testing in from the CRA base before extending it to a more involved config like airbnb.
> Run eslint during lint command / test workflow

- src/pages/overlay/components/overlay/Overlay.tsx
- src/pages/panel/components/ambassadorPanel/AmbassadorPanel.tsx
- src/utils/chatCommand.ts
Resolves #50
Running the same command multiple times will re-awaken the overlay to show the same ambassador again. This switches the chat hook from returning the last ambassador to calling a provided callback when a new ambassador command is run.
> Allow same command repeatedly, use callback instead of return

- src/pages/overlay/App.module.scss
- src/pages/overlay/components/overlay/overlay.module.scss
- src/pages/overlay/components/overlaySettings/overlaySettings.module.scss
Noticed a few issues with how the app was sleeping now (settings weren't fading, elements still showed cursors). I think this might've broken with the intro stuff being pushed.
This fades the opacity at the app level, and disables pointer events for everything within the app while sleeping. The user can still interact with the app (mouse movements) to wake again.
Each component can then do anything extra when sleeping, like sliding out of frame.
> Fix sleeping styling

- src/pages/overlay/components/overlay/Overlay.tsx
Resolves #61.
This is slightly hacky, in that it relies on checking the parent of the overlay itself, so that click on setting doesn't close the panels. It should work as desired though.
> Close overlay panels on click in body

- README.md
Twitch Developer Rig has been deprecated, and no longer allows new projects to be added.
> Remove developer rig from README

- config-overrides.js
- public/index.html
- src/template.html
This makes the index.html a list of links to the various views (`video_overlay.html`, `panel.html` and `mobile.html`) and use `src/template.html` instead to generate the view htmls.
This makes it easier to open the views on the dev server not having to type in the paths.
> Make index.html link to views

- src/pages/overlay/App.tsx
- src/pages/overlay/components/overlay/Overlay.tsx
- src/pages/overlay/components/overlay/settings/Settings.tsx
- src/pages/overlay/hooks/useHiddenCursor.ts
- src/pages/overlay/hooks/useIntelligentTimer.ts
- src/pages/overlay/hooks/useSettings.tsx
- src/pages/overlay/hooks/useSleeping.tsx
- src/pages/overlay/hooks/useStoredSettings.tsx
- src/pages/overlay/index.tsx
Should be no real functionality change, just cleaning up a lot of the app logic that was reliant on passing props everywhere into proper hooks
> Move core app logic to proper hooks/contexts

- src/pages/overlay/App.tsx
- src/pages/overlay/hooks/useScrolling.ts
- src/pages/overlay/hooks/useScrolling.tsx
Fixes #111 
When a chat command is run, and the user doesn't interact with the page, the card shown should auto-dismiss after 10s. When the user next interacts, the extension should not be showing any card.
> Move scroll detection to hook, require user event

- src/pages/overlay/components/overlay/Overlay.tsx
- src/pages/overlay/components/overlay/ambassadors/Ambassadors.tsx
Bug repro:
- as a mod use chat command to open ambassador card (e.g. `!nilla`)
- as a viewer de-select the ambassador or select a different ambassador
- as a mod use chat command to open the same ambassador card (e.g. `!nilla`)
- expected: the ambassador of the chat command opens, actual: the overlay opens without select or the viewer selected card
> Fix ambassador card not reopening on repeated commands

- .eslintrc.json
- src/pages/overlay/components/buttons/Buttons.tsx
- src/pages/overlay/components/card/Card.tsx
- src/pages/overlay/components/overlay/settings/Settings.tsx
- src/pages/overlay/components/overlay/welcome/Welcome.tsx
- src/pages/overlay/index.tsx
- src/pages/panel/App.tsx
- src/pages/panel/components/nav/Nav.tsx
- src/pages/panel/index.tsx
- src/utils/global/ambassadorCard/AmbassadorCard.tsx
We're using the react-jsx transform, which doesn't require React be imported into every JSX usage (https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html)
> Remove React imports for JSX

- src/components/ambassadorButton/ambassadorButton.module.scss
- src/components/ambassadorCard/ambassadorCard.module.scss
- src/pages/overlay/components/buttons/buttons.module.scss
- src/pages/overlay/components/card/card.module.scss
- src/pages/overlay/components/overlay/ambassadors/ambassadors.module.scss
- src/pages/overlay/components/toggle/Toggle.tsx
- src/pages/overlay/components/toggle/toggle.module.scss
- src/variables.scss
Resolves #129 by replacing the existing switch toggle styling with custom checkboxes.
This PR also includes some consistency cleanup for the outline style we apply to things on hover, and a consistent shadow across all the elements.
> Replace settings switch toggles with checkboxes

- src/components/tooltip/Tooltip.tsx
- src/components/tooltip/tooltip.module.scss
Resolves #115 
Wrote a condition that checks whether tooltip fits to the right, if not tooltip is shown on the top. Also changed the position of the triangle to the bottom of the tooltip for that case.
> Change to tooltip to fit mobile panel

- src/pages/overlay/components/overlay/ambassadors/ambassadors.module.scss
Much as this looked really nice in testing, on the actual extension this caused the video of the stream itself to be blurred, _and_ the blur doesn't work while the translate animation occurs, so it looks really janky. Removing it and relying on just the fade, which still looks fine.
> Remove overlay list blur

- package-lock.json
- package.json
- src/pages/overlay/components/overlay/Overlay.tsx
- src/utils/dom.ts
Fixes #54 
Since I am not a React expert and this is my first time developing a Twitch extension, I welcome any critiques 😁 
I can remove cd084dcc9a23a8016967889e16da67b821b23510 if desired, but I believe using a tool like `cross-env` is necessary to set env variables inline on Windows.
> Don't fullscreen the video when double-clicking components

- .env.sample
- src/hooks/useChatCommand.ts
Resolves #152
Make sure your `.env` is updated to test, and this will need to be tested with a localhost extension on Twitch itself, as it will only connect to the extra channels when it knows what Twitch channel it is on.
> Add extra channels to connect to when not in default

- src/hooks/useChannel.ts
- src/hooks/useChatCommand.ts
We have `alveussanctuary` in the default set of channel names, so when the extension is active in this channel it should not be watching the extra channel names including `alveusgg`. However, as seen in recent collaborations, commands run in `alveusgg` where controlling the extension in `alveussanctuary`.
After some investigation, the issue stems from the `broadcaster_name` for `alveussanctuary` actually being `AlveusSanctuary`. I've solved this in a few different places for some redundancy -- switching to `broadcaster_login` gives us back `alveussanctuary` instead, and then I've ensured we're normalizing all the values used for these name checks to always be lowercase.
> Ensure consistent string case for channel name checks

- README.md
To satisfy updated Twitch requirements.
> Add note to README about user data

- src/pages/overlay/components/overlay/Overlay.tsx
`settings.disableChatPopup` was a dependency of the callback being passed into the chat connection, which is a changing object (while stable in a `useMemo`, settings change when a command is run, which recreates the object). This caused the chat to reconnect every time the React component updated, such as when a chat command was run.
| Before | After |
|-|-|
| ![image](https://github.com/user-attachments/assets/49d8c0d6-fd90-409f-8aff-1ac65bafce5c) | ![image](https://github.com/user-attachments/assets/0850e9f0-ec1c-464e-8088-03d3684690aa) |
> Don't continually recreate chat connection

- .github/dependabot.yml
Same config that we've settled on over in https://github.com/alveusgg/alveusgg, sans the pnpmfile bit as we don't use pnpm here and hopefully npm shouldn't have the same GitHub SSH deps issue.
> Add dependabot config for GitHub Actions + NPM

- src/utils/dom.ts
Using tab to focus on one of the overlay buttons, using 'Enter' on the keyboard will now correctly toggle the panel.
Fixes #222 -- spamming enter when focused on a panel button will no longer cause the extension to loop, as we're no longer double-calling the setting setter for which panel is open (previously 'Enter' would invoke the body click logic to dismiss the panel, and then immediately also invoke the button click logic to open the panel, causing a state race and loop).
> Handle keyboard-triggered click events correctly

- .github/dependabot.yml
- .npmrc
Same changes as in https://github.com/alveusgg/alveusgg/pull/989, also tested in a fork.
> Allow Dependabot to access @alveusgg/data from GitHub Packages

- src/components/AmbassadorButton.tsx
- src/components/AmbassadorCard.tsx
- src/pages/overlay/components/Buttons.tsx
- src/pages/overlay/components/Toggle.tsx
- src/pages/overlay/components/overlay/Ambassadors.tsx
- src/pages/panel/components/Nav.tsx
Looks like I missed this in #237 -- the v4 upgrade guide mentions `ring` changing, but not `outline`.
> Fix outline highlight width on elements

- README.md
- package.json
- src/hooks/useAmbassadors.tsx
- src/hooks/useChatCommand.ts
- src/pages/overlay/components/Buttons.tsx
- src/pages/overlay/hooks/useSettings.tsx
- src/utils/dateManager.ts
- tsconfig.json
In a similar vein to https://github.com/alveusgg/alveusgg/pull/1063, this enables `erasableSyntaxOnly` now that we have TS 5.8, and then also enables `verbatimModuleSyntax` which works alongside it to make sure type imports are marked as such. Also enables `noUncheckedIndexedAccess` as we had that enabled in alveusgg/alveusgg but not here.
> Enable erasableSyntaxOnly + verbatimModuleSyntax + noUncheckedIndexedAccess

- .github/workflows/checks.yml
https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/ is a good reminder that we should all pin our GitHub Actions dependencies to specific hashes that we trust, rather than mutable tags.
cc https://github.com/alveusgg/alveusgg/pull/1089
> Pin all GitHub Actions dependencies to specific hashes

- .env.sample
- package.json
- pnpm-lock.yaml
- src/pages/overlay/components/overlay/Ambassadors.tsx
- src/react-app-env.d.ts
- src/utils/dateManager.ts
It seems a bit odd that ambassadors show their birthday as soon as midnight UTC is hit. It also felt weird to make it work based on local time (where APAC users would see ambassador birthdays the day before essentially). So, using Alveus' timezone seems like the right option but doing timezone logic in native JS is awful so I've introduced Luxon to handle it as we do on the website.
> Use Alveus timezone for birthday/age logic

- src/components/AmbassadorButton.tsx
- src/components/AmbassadorCard.tsx
- src/components/Card.tsx
- src/components/Ring.tsx
- src/pages/overlay/components/Buttons.tsx
- src/pages/overlay/components/overlay/Ambassadors.tsx
Following a similar visual style to what we've been doing on the site recently, to help make the buttons/cards stand out more against the stream content.
> Add light box rings to buttons + cards

- package.json
- pnpm-lock.yaml
- src/hooks/useAmbassadors.tsx
- webpack.config.ts
cc https://github.com/alveusgg/data/pull/147
> Update data (tsup build)
